allowBuilds:
  "@tailwindcss/oxide": true
  "esbuild": true
  "sharp": true

overrides:
  "vite": 'catalog:'
  "vitest": 'catalog:'
  "serialize-javascript@>=5.0.0 <7.0.3": ">=7.0.3"
  "dompurify@<3.4.12": ">=3.4.12"
  "brace-expansion@<5.0.8": ">=5.0.8"
  "esbuild@>=0.27.3 <0.28.1": ">=0.28.1"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.2.5
  vitest: 4.1.10
  vite-plus: ^0.2.5
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
patchedDependencies:
  '@tanstack/router-core@1.171.15': patches/@tanstack__router-core@1.171.15.patch
