export interface City {
  /** Country for search context */
  country: string;
  /** IANA timezone identifier, e.g. "America/New_York" */
  id: string;
  /** Display name, e.g. "New York" */
  name: string;
  /** IANA timezone identifier (same as id, kept separate for clarity) */
  timezone: string;
  /** Working hours end, 0-23 (exclusive) */
  workEnd: number;
  /** Working hours start, 0-23 */
  workStart: number;
}

export const CITIES: ReadonlyArray<City> = [
  {
    country: 'New Zealand',
    id: 'pacific/auckland',
    name: 'Auckland',
    timezone: 'Pacific/Auckland',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Australia',
    id: 'australia/sydney',
    name: 'Sydney',
    timezone: 'Australia/Sydney',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Japan',
    id: 'asia/tokyo',
    name: 'Tokyo',
    timezone: 'Asia/Tokyo',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'China',
    id: 'asia/shanghai',
    name: 'Shanghai',
    timezone: 'Asia/Shanghai',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Singapore',
    id: 'asia/singapore',
    name: 'Singapore',
    timezone: 'Asia/Singapore',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'UAE',
    id: 'asia/dubai',
    name: 'Dubai',
    timezone: 'Asia/Dubai',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'India',
    id: 'asia/kolkata',
    name: 'Kolkata',
    timezone: 'Asia/Kolkata',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Pakistan',
    id: 'asia/karachi',
    name: 'Karachi',
    timezone: 'Asia/Karachi',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Bangladesh',
    id: 'asia/dhaka',
    name: 'Dhaka',
    timezone: 'Asia/Dhaka',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Thailand',
    id: 'asia/bangkok',
    name: 'Bangkok',
    timezone: 'Asia/Bangkok',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Indonesia',
    id: 'asia/jakarta',
    name: 'Jakarta',
    timezone: 'Asia/Jakarta',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'South Korea',
    id: 'asia/seoul',
    name: 'Seoul',
    timezone: 'Asia/Seoul',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'China',
    id: 'asia/hong_kong',
    name: 'Hong Kong',
    timezone: 'Asia/Hong_Kong',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Russia',
    id: 'europe/moscow',
    name: 'Moscow',
    timezone: 'Europe/Moscow',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Turkey',
    id: 'europe/istanbul',
    name: 'Istanbul',
    timezone: 'Europe/Istanbul',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'UK',
    id: 'europe/london',
    name: 'London',
    timezone: 'Europe/London',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'France',
    id: 'europe/paris',
    name: 'Paris',
    timezone: 'Europe/Paris',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Germany',
    id: 'europe/berlin',
    name: 'Berlin',
    timezone: 'Europe/Berlin',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Spain',
    id: 'europe/madrid',
    name: 'Madrid',
    timezone: 'Europe/Madrid',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Italy',
    id: 'europe/rome',
    name: 'Rome',
    timezone: 'Europe/Rome',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Netherlands',
    id: 'europe/amsterdam',
    name: 'Amsterdam',
    timezone: 'Europe/Amsterdam',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Switzerland',
    id: 'europe/zurich',
    name: 'Zurich',
    timezone: 'Europe/Zurich',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Sweden',
    id: 'europe/stockholm',
    name: 'Stockholm',
    timezone: 'Europe/Stockholm',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Norway',
    id: 'europe/oslo',
    name: 'Oslo',
    timezone: 'Europe/Oslo',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Denmark',
    id: 'europe/copenhagen',
    name: 'Copenhagen',
    timezone: 'Europe/Copenhagen',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Finland',
    id: 'europe/helsinki',
    name: 'Helsinki',
    timezone: 'Europe/Helsinki',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Greece',
    id: 'europe/athens',
    name: 'Athens',
    timezone: 'Europe/Athens',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Poland',
    id: 'europe/warsaw',
    name: 'Warsaw',
    timezone: 'Europe/Warsaw',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Czech Republic',
    id: 'europe/prague',
    name: 'Prague',
    timezone: 'Europe/Prague',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Hungary',
    id: 'europe/budapest',
    name: 'Budapest',
    timezone: 'Europe/Budapest',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Egypt',
    id: 'africa/cairo',
    name: 'Cairo',
    timezone: 'Africa/Cairo',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Nigeria',
    id: 'africa/lagos',
    name: 'Lagos',
    timezone: 'Africa/Lagos',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'South Africa',
    id: 'africa/johannesburg',
    name: 'Johannesburg',
    timezone: 'Africa/Johannesburg',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Kenya',
    id: 'africa/nairobi',
    name: 'Nairobi',
    timezone: 'Africa/Nairobi',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/anchorage',
    name: 'Anchorage',
    timezone: 'America/Anchorage',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/los_angeles',
    name: 'Los Angeles',
    timezone: 'America/Los_Angeles',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/denver',
    name: 'Denver',
    timezone: 'America/Denver',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/chicago',
    name: 'Chicago',
    timezone: 'America/Chicago',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/new_york',
    name: 'New York',
    timezone: 'America/New_York',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Canada',
    id: 'america/toronto',
    name: 'Toronto',
    timezone: 'America/Toronto',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Canada',
    id: 'america/vancouver',
    name: 'Vancouver',
    timezone: 'America/Vancouver',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Mexico',
    id: 'america/mexico_city',
    name: 'Mexico City',
    timezone: 'America/Mexico_City',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Brazil',
    id: 'america/sao_paulo',
    name: 'São Paulo',
    timezone: 'America/Sao_Paulo',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Argentina',
    id: 'america/argentina/buenos_aires',
    name: 'Buenos Aires',
    timezone: 'America/Argentina/Buenos_Aires',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Chile',
    id: 'america/santiago',
    name: 'Santiago',
    timezone: 'America/Santiago',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Colombia',
    id: 'america/bogota',
    name: 'Bogotá',
    timezone: 'America/Bogota',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Peru',
    id: 'america/lima',
    name: 'Lima',
    timezone: 'America/Lima',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Venezuela',
    id: 'america/caracas',
    name: 'Caracas',
    timezone: 'America/Caracas',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Canada',
    id: 'america/halifax',
    name: 'Halifax',
    timezone: 'America/Halifax',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/phoenix',
    name: 'Phoenix',
    timezone: 'America/Phoenix',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/honolulu',
    name: 'Honolulu',
    timezone: 'Pacific/Honolulu',
    workEnd: 17,
    workStart: 9,
  },
];

export const DEFAULT_CITY_IDS: ReadonlyArray<string> = [
  'america/los_angeles',
  'america/new_york',
  'europe/london',
  'asia/tokyo',
];

export function getCityById(id: string): City | undefined {
  return CITIES.find((c) => c.id === id);
}

export function searchCities(query: string): Array<City> {
  const q = query.toLowerCase().trim();
  if (!q) {
    return [];
  }
  return CITIES.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.country.toLowerCase().includes(q) ||
      c.timezone.toLowerCase().includes(q)
  );
}
