import type { City } from './cities';

export const ASIA_OCEANIA_CITIES: ReadonlyArray<City> = [
  {
    country: 'New Zealand',
    id: 'pacific/auckland',
    name: 'Auckland',
    timezone: 'Pacific/Auckland',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Australia',
    id: 'australia/sydney',
    name: 'Sydney',
    timezone: 'Australia/Sydney',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Australia',
    id: 'australia/melbourne',
    name: 'Melbourne',
    timezone: 'Australia/Melbourne',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Australia',
    id: 'australia/brisbane',
    name: 'Brisbane',
    timezone: 'Australia/Brisbane',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Australia',
    id: 'australia/perth',
    name: 'Perth',
    timezone: 'Australia/Perth',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Japan',
    id: 'asia/tokyo',
    name: 'Tokyo',
    timezone: 'Asia/Tokyo',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'China',
    id: 'asia/shanghai',
    name: 'Shanghai',
    timezone: 'Asia/Shanghai',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Singapore',
    id: 'asia/singapore',
    name: 'Singapore',
    timezone: 'Asia/Singapore',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'UAE',
    id: 'asia/dubai',
    name: 'Dubai',
    timezone: 'Asia/Dubai',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'India',
    id: 'asia/kolkata',
    name: 'Kolkata',
    timezone: 'Asia/Kolkata',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Pakistan',
    id: 'asia/karachi',
    name: 'Karachi',
    timezone: 'Asia/Karachi',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Bangladesh',
    id: 'asia/dhaka',
    name: 'Dhaka',
    timezone: 'Asia/Dhaka',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Thailand',
    id: 'asia/bangkok',
    name: 'Bangkok',
    timezone: 'Asia/Bangkok',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Indonesia',
    id: 'asia/jakarta',
    name: 'Jakarta',
    timezone: 'Asia/Jakarta',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'South Korea',
    id: 'asia/seoul',
    name: 'Seoul',
    timezone: 'Asia/Seoul',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'China',
    id: 'asia/hong_kong',
    name: 'Hong Kong',
    timezone: 'Asia/Hong_Kong',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Philippines',
    id: 'asia/manila',
    name: 'Manila',
    timezone: 'Asia/Manila',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Taiwan',
    id: 'asia/taipei',
    name: 'Taipei',
    timezone: 'Asia/Taipei',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Malaysia',
    id: 'asia/kuala_lumpur',
    name: 'Kuala Lumpur',
    timezone: 'Asia/Kuala_Lumpur',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Saudi Arabia',
    id: 'asia/riyadh',
    name: 'Riyadh',
    timezone: 'Asia/Riyadh',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Qatar',
    id: 'asia/doha',
    name: 'Doha',
    timezone: 'Asia/Qatar',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Israel',
    id: 'asia/tel_aviv',
    name: 'Tel Aviv',
    timezone: 'Asia/Jerusalem',
    workEnd: 17,
    workStart: 9,
  },
];
