import type { City } from './cities';

export const AMERICAS_CITIES: ReadonlyArray<City> = [
  {
    country: 'USA',
    id: 'america/anchorage',
    name: 'Anchorage',
    timezone: 'America/Anchorage',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/los_angeles',
    name: 'Los Angeles',
    timezone: 'America/Los_Angeles',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/denver',
    name: 'Denver',
    timezone: 'America/Denver',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/chicago',
    name: 'Chicago',
    timezone: 'America/Chicago',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/new_york',
    name: 'New York',
    timezone: 'America/New_York',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/boston',
    name: 'Boston',
    timezone: 'America/New_York',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/atlanta',
    name: 'Atlanta',
    timezone: 'America/New_York',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/miami',
    name: 'Miami',
    timezone: 'America/New_York',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/detroit',
    name: 'Detroit',
    timezone: 'America/Detroit',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/dallas',
    name: 'Dallas',
    timezone: 'America/Chicago',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/houston',
    name: 'Houston',
    timezone: 'America/Chicago',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/san_francisco',
    name: 'San Francisco',
    timezone: 'America/Los_Angeles',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/san_diego',
    name: 'San Diego',
    timezone: 'America/Los_Angeles',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/seattle',
    name: 'Seattle',
    timezone: 'America/Los_Angeles',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Canada',
    id: 'america/toronto',
    name: 'Toronto',
    timezone: 'America/Toronto',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Canada',
    id: 'america/vancouver',
    name: 'Vancouver',
    timezone: 'America/Vancouver',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Mexico',
    id: 'america/mexico_city',
    name: 'Mexico City',
    timezone: 'America/Mexico_City',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Brazil',
    id: 'america/sao_paulo',
    name: 'São Paulo',
    timezone: 'America/Sao_Paulo',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Argentina',
    id: 'america/argentina/buenos_aires',
    name: 'Buenos Aires',
    timezone: 'America/Argentina/Buenos_Aires',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Chile',
    id: 'america/santiago',
    name: 'Santiago',
    timezone: 'America/Santiago',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Colombia',
    id: 'america/bogota',
    name: 'Bogotá',
    timezone: 'America/Bogota',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Peru',
    id: 'america/lima',
    name: 'Lima',
    timezone: 'America/Lima',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Venezuela',
    id: 'america/caracas',
    name: 'Caracas',
    timezone: 'America/Caracas',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Canada',
    id: 'america/halifax',
    name: 'Halifax',
    timezone: 'America/Halifax',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/phoenix',
    name: 'Phoenix',
    timezone: 'America/Phoenix',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'USA',
    id: 'america/honolulu',
    name: 'Honolulu',
    timezone: 'Pacific/Honolulu',
    workEnd: 17,
    workStart: 9,
  },
];
