import type { City } from './cities';

export const EUROPE_AFRICA_CITIES: ReadonlyArray<City> = [
  {
    country: 'Russia',
    id: 'europe/moscow',
    name: 'Moscow',
    timezone: 'Europe/Moscow',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Turkey',
    id: 'europe/istanbul',
    name: 'Istanbul',
    timezone: 'Europe/Istanbul',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'UK',
    id: 'europe/london',
    name: 'London',
    timezone: 'Europe/London',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'France',
    id: 'europe/paris',
    name: 'Paris',
    timezone: 'Europe/Paris',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Germany',
    id: 'europe/berlin',
    name: 'Berlin',
    timezone: 'Europe/Berlin',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Spain',
    id: 'europe/madrid',
    name: 'Madrid',
    timezone: 'Europe/Madrid',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Italy',
    id: 'europe/rome',
    name: 'Rome',
    timezone: 'Europe/Rome',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Netherlands',
    id: 'europe/amsterdam',
    name: 'Amsterdam',
    timezone: 'Europe/Amsterdam',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Switzerland',
    id: 'europe/zurich',
    name: 'Zurich',
    timezone: 'Europe/Zurich',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Sweden',
    id: 'europe/stockholm',
    name: 'Stockholm',
    timezone: 'Europe/Stockholm',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Norway',
    id: 'europe/oslo',
    name: 'Oslo',
    timezone: 'Europe/Oslo',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Denmark',
    id: 'europe/copenhagen',
    name: 'Copenhagen',
    timezone: 'Europe/Copenhagen',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Finland',
    id: 'europe/helsinki',
    name: 'Helsinki',
    timezone: 'Europe/Helsinki',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Greece',
    id: 'europe/athens',
    name: 'Athens',
    timezone: 'Europe/Athens',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Poland',
    id: 'europe/warsaw',
    name: 'Warsaw',
    timezone: 'Europe/Warsaw',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Czech Republic',
    id: 'europe/prague',
    name: 'Prague',
    timezone: 'Europe/Prague',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Hungary',
    id: 'europe/budapest',
    name: 'Budapest',
    timezone: 'Europe/Budapest',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Egypt',
    id: 'africa/cairo',
    name: 'Cairo',
    timezone: 'Africa/Cairo',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Nigeria',
    id: 'africa/lagos',
    name: 'Lagos',
    timezone: 'Africa/Lagos',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'South Africa',
    id: 'africa/johannesburg',
    name: 'Johannesburg',
    timezone: 'Africa/Johannesburg',
    workEnd: 17,
    workStart: 9,
  },
  {
    country: 'Kenya',
    id: 'africa/nairobi',
    name: 'Nairobi',
    timezone: 'Africa/Nairobi',
    workEnd: 17,
    workStart: 9,
  },
];
