/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteRouteImport } from './routes/tools/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsZippyImgIndexRouteImport } from './routes/tools/zippy-img/index'
import { Route as ToolsWaLinkHelperIndexRouteImport } from './routes/tools/wa-link-helper/index'
import { Route as ToolsJsPerfComparatorIndexRouteImport } from './routes/tools/js-perf-comparator/index'

const ToolsRouteRoute = ToolsRouteRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsZippyImgIndexRoute = ToolsZippyImgIndexRouteImport.update({
  id: '/zippy-img/',
  path: '/zippy-img/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsWaLinkHelperIndexRoute = ToolsWaLinkHelperIndexRouteImport.update({
  id: '/wa-link-helper/',
  path: '/wa-link-helper/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsJsPerfComparatorIndexRoute =
  ToolsJsPerfComparatorIndexRouteImport.update({
    id: '/js-perf-comparator/',
    path: '/js-perf-comparator/',
    getParentRoute: () => ToolsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools': typeof ToolsRouteRouteWithChildren
  '/tools/js-perf-comparator/': typeof ToolsJsPerfComparatorIndexRoute
  '/tools/wa-link-helper/': typeof ToolsWaLinkHelperIndexRoute
  '/tools/zippy-img/': typeof ToolsZippyImgIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools': typeof ToolsRouteRouteWithChildren
  '/tools/js-perf-comparator': typeof ToolsJsPerfComparatorIndexRoute
  '/tools/wa-link-helper': typeof ToolsWaLinkHelperIndexRoute
  '/tools/zippy-img': typeof ToolsZippyImgIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools': typeof ToolsRouteRouteWithChildren
  '/tools/js-perf-comparator/': typeof ToolsJsPerfComparatorIndexRoute
  '/tools/wa-link-helper/': typeof ToolsWaLinkHelperIndexRoute
  '/tools/zippy-img/': typeof ToolsZippyImgIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tools'
    | '/tools/js-perf-comparator/'
    | '/tools/wa-link-helper/'
    | '/tools/zippy-img/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tools'
    | '/tools/js-perf-comparator'
    | '/tools/wa-link-helper'
    | '/tools/zippy-img'
  id:
    | '__root__'
    | '/'
    | '/tools'
    | '/tools/js-perf-comparator/'
    | '/tools/wa-link-helper/'
    | '/tools/zippy-img/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsRouteRoute: typeof ToolsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/zippy-img/': {
      id: '/tools/zippy-img/'
      path: '/zippy-img'
      fullPath: '/tools/zippy-img/'
      preLoaderRoute: typeof ToolsZippyImgIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/tools/wa-link-helper/': {
      id: '/tools/wa-link-helper/'
      path: '/wa-link-helper'
      fullPath: '/tools/wa-link-helper/'
      preLoaderRoute: typeof ToolsWaLinkHelperIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/tools/js-perf-comparator/': {
      id: '/tools/js-perf-comparator/'
      path: '/js-perf-comparator'
      fullPath: '/tools/js-perf-comparator/'
      preLoaderRoute: typeof ToolsJsPerfComparatorIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
  }
}

interface ToolsRouteRouteChildren {
  ToolsJsPerfComparatorIndexRoute: typeof ToolsJsPerfComparatorIndexRoute
  ToolsWaLinkHelperIndexRoute: typeof ToolsWaLinkHelperIndexRoute
  ToolsZippyImgIndexRoute: typeof ToolsZippyImgIndexRoute
}

const ToolsRouteRouteChildren: ToolsRouteRouteChildren = {
  ToolsJsPerfComparatorIndexRoute: ToolsJsPerfComparatorIndexRoute,
  ToolsWaLinkHelperIndexRoute: ToolsWaLinkHelperIndexRoute,
  ToolsZippyImgIndexRoute: ToolsZippyImgIndexRoute,
}

const ToolsRouteRouteWithChildren = ToolsRouteRoute._addFileChildren(
  ToolsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsRouteRoute: ToolsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
