/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ToolsRouteRouteImport } from './routes/_tools/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsZippyImgIndexRouteImport } from './routes/_tools/zippy-img/index'
import { Route as ToolsWaLinkHelperIndexRouteImport } from './routes/_tools/wa-link-helper/index'
import { Route as ToolsUaCheckIndexRouteImport } from './routes/_tools/ua-check/index'
import { Route as ToolsQrcodeGeneratorIndexRouteImport } from './routes/_tools/qrcode-generator/index'
import { Route as ToolsJsPerfComparatorIndexRouteImport } from './routes/_tools/js-perf-comparator/index'
import { Route as ToolsEvChargingEstimatorIndexRouteImport } from './routes/_tools/ev-charging-estimator/index'
import { Route as ToolsAddToCalendarIndexRouteImport } from './routes/_tools/add-to-calendar/index'

const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRouteRoute = ToolsRouteRouteImport.update({
  id: '/_tools',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsZippyImgIndexRoute = ToolsZippyImgIndexRouteImport.update({
  id: '/zippy-img/',
  path: '/zippy-img/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsWaLinkHelperIndexRoute = ToolsWaLinkHelperIndexRouteImport.update({
  id: '/wa-link-helper/',
  path: '/wa-link-helper/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsUaCheckIndexRoute = ToolsUaCheckIndexRouteImport.update({
  id: '/ua-check/',
  path: '/ua-check/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsQrcodeGeneratorIndexRoute =
  ToolsQrcodeGeneratorIndexRouteImport.update({
    id: '/qrcode-generator/',
    path: '/qrcode-generator/',
    getParentRoute: () => ToolsRouteRoute,
  } as any)
const ToolsJsPerfComparatorIndexRoute =
  ToolsJsPerfComparatorIndexRouteImport.update({
    id: '/js-perf-comparator/',
    path: '/js-perf-comparator/',
    getParentRoute: () => ToolsRouteRoute,
  } as any)
const ToolsEvChargingEstimatorIndexRoute =
  ToolsEvChargingEstimatorIndexRouteImport.update({
    id: '/ev-charging-estimator/',
    path: '/ev-charging-estimator/',
    getParentRoute: () => ToolsRouteRoute,
  } as any)
const ToolsAddToCalendarIndexRoute = ToolsAddToCalendarIndexRouteImport.update({
  id: '/add-to-calendar/',
  path: '/add-to-calendar/',
  getParentRoute: () => ToolsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/add-to-calendar/': typeof ToolsAddToCalendarIndexRoute
  '/ev-charging-estimator/': typeof ToolsEvChargingEstimatorIndexRoute
  '/js-perf-comparator/': typeof ToolsJsPerfComparatorIndexRoute
  '/qrcode-generator/': typeof ToolsQrcodeGeneratorIndexRoute
  '/ua-check/': typeof ToolsUaCheckIndexRoute
  '/wa-link-helper/': typeof ToolsWaLinkHelperIndexRoute
  '/zippy-img/': typeof ToolsZippyImgIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/add-to-calendar': typeof ToolsAddToCalendarIndexRoute
  '/ev-charging-estimator': typeof ToolsEvChargingEstimatorIndexRoute
  '/js-perf-comparator': typeof ToolsJsPerfComparatorIndexRoute
  '/qrcode-generator': typeof ToolsQrcodeGeneratorIndexRoute
  '/ua-check': typeof ToolsUaCheckIndexRoute
  '/wa-link-helper': typeof ToolsWaLinkHelperIndexRoute
  '/zippy-img': typeof ToolsZippyImgIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tools': typeof ToolsRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/_tools/add-to-calendar/': typeof ToolsAddToCalendarIndexRoute
  '/_tools/ev-charging-estimator/': typeof ToolsEvChargingEstimatorIndexRoute
  '/_tools/js-perf-comparator/': typeof ToolsJsPerfComparatorIndexRoute
  '/_tools/qrcode-generator/': typeof ToolsQrcodeGeneratorIndexRoute
  '/_tools/ua-check/': typeof ToolsUaCheckIndexRoute
  '/_tools/wa-link-helper/': typeof ToolsWaLinkHelperIndexRoute
  '/_tools/zippy-img/': typeof ToolsZippyImgIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/add-to-calendar/'
    | '/ev-charging-estimator/'
    | '/js-perf-comparator/'
    | '/qrcode-generator/'
    | '/ua-check/'
    | '/wa-link-helper/'
    | '/zippy-img/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/add-to-calendar'
    | '/ev-charging-estimator'
    | '/js-perf-comparator'
    | '/qrcode-generator'
    | '/ua-check'
    | '/wa-link-helper'
    | '/zippy-img'
  id:
    | '__root__'
    | '/'
    | '/_tools'
    | '/changelog'
    | '/_tools/add-to-calendar/'
    | '/_tools/ev-charging-estimator/'
    | '/_tools/js-perf-comparator/'
    | '/_tools/qrcode-generator/'
    | '/_tools/ua-check/'
    | '/_tools/wa-link-helper/'
    | '/_tools/zippy-img/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsRouteRoute: typeof ToolsRouteRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tools': {
      id: '/_tools'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ToolsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tools/zippy-img/': {
      id: '/_tools/zippy-img/'
      path: '/zippy-img'
      fullPath: '/zippy-img/'
      preLoaderRoute: typeof ToolsZippyImgIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/wa-link-helper/': {
      id: '/_tools/wa-link-helper/'
      path: '/wa-link-helper'
      fullPath: '/wa-link-helper/'
      preLoaderRoute: typeof ToolsWaLinkHelperIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/ua-check/': {
      id: '/_tools/ua-check/'
      path: '/ua-check'
      fullPath: '/ua-check/'
      preLoaderRoute: typeof ToolsUaCheckIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/qrcode-generator/': {
      id: '/_tools/qrcode-generator/'
      path: '/qrcode-generator'
      fullPath: '/qrcode-generator/'
      preLoaderRoute: typeof ToolsQrcodeGeneratorIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/js-perf-comparator/': {
      id: '/_tools/js-perf-comparator/'
      path: '/js-perf-comparator'
      fullPath: '/js-perf-comparator/'
      preLoaderRoute: typeof ToolsJsPerfComparatorIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/ev-charging-estimator/': {
      id: '/_tools/ev-charging-estimator/'
      path: '/ev-charging-estimator'
      fullPath: '/ev-charging-estimator/'
      preLoaderRoute: typeof ToolsEvChargingEstimatorIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/add-to-calendar/': {
      id: '/_tools/add-to-calendar/'
      path: '/add-to-calendar'
      fullPath: '/add-to-calendar/'
      preLoaderRoute: typeof ToolsAddToCalendarIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
  }
}

interface ToolsRouteRouteChildren {
  ToolsAddToCalendarIndexRoute: typeof ToolsAddToCalendarIndexRoute
  ToolsEvChargingEstimatorIndexRoute: typeof ToolsEvChargingEstimatorIndexRoute
  ToolsJsPerfComparatorIndexRoute: typeof ToolsJsPerfComparatorIndexRoute
  ToolsQrcodeGeneratorIndexRoute: typeof ToolsQrcodeGeneratorIndexRoute
  ToolsUaCheckIndexRoute: typeof ToolsUaCheckIndexRoute
  ToolsWaLinkHelperIndexRoute: typeof ToolsWaLinkHelperIndexRoute
  ToolsZippyImgIndexRoute: typeof ToolsZippyImgIndexRoute
}

const ToolsRouteRouteChildren: ToolsRouteRouteChildren = {
  ToolsAddToCalendarIndexRoute: ToolsAddToCalendarIndexRoute,
  ToolsEvChargingEstimatorIndexRoute: ToolsEvChargingEstimatorIndexRoute,
  ToolsJsPerfComparatorIndexRoute: ToolsJsPerfComparatorIndexRoute,
  ToolsQrcodeGeneratorIndexRoute: ToolsQrcodeGeneratorIndexRoute,
  ToolsUaCheckIndexRoute: ToolsUaCheckIndexRoute,
  ToolsWaLinkHelperIndexRoute: ToolsWaLinkHelperIndexRoute,
  ToolsZippyImgIndexRoute: ToolsZippyImgIndexRoute,
}

const ToolsRouteRouteWithChildren = ToolsRouteRoute._addFileChildren(
  ToolsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsRouteRoute: ToolsRouteRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
