/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsRouteRouteImport } from './routes/_tools/route'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as HomepageIndexRouteImport } from './routes/homepage/index'
import { Route as ToolsAddToCalendarIndexRouteImport } from './routes/_tools/add-to-calendar/index'
import { Route as ToolsBase64IndexRouteImport } from './routes/_tools/base64/index'
import { Route as ToolsCaseConverterIndexRouteImport } from './routes/_tools/case-converter/index'
import { Route as ToolsColorConverterIndexRouteImport } from './routes/_tools/color-converter/index'
import { Route as ToolsCronParserIndexRouteImport } from './routes/_tools/cron-parser/index'
import { Route as ToolsCsvConverterIndexRouteImport } from './routes/_tools/csv-converter/index'
import { Route as ToolsEvChargingIndexRouteImport } from './routes/_tools/ev-charging/index'
import { Route as ToolsHashGeneratorIndexRouteImport } from './routes/_tools/hash-generator/index'
import { Route as ToolsHtmlEntitiesIndexRouteImport } from './routes/_tools/html-entities/index'
import { Route as ToolsJsPerfIndexRouteImport } from './routes/_tools/js-perf/index'
import { Route as ToolsJsonFormatterIndexRouteImport } from './routes/_tools/json-formatter/index'
import { Route as ToolsJsonToTsIndexRouteImport } from './routes/_tools/json-to-ts/index'
import { Route as ToolsJwtDecoderIndexRouteImport } from './routes/_tools/jwt-decoder/index'
import { Route as ToolsMarkdownPreviewIndexRouteImport } from './routes/_tools/markdown-preview/index'
import { Route as ToolsNumberBaseIndexRouteImport } from './routes/_tools/number-base/index'
import { Route as ToolsPasswordGeneratorIndexRouteImport } from './routes/_tools/password-generator/index'
import { Route as ToolsQrcodeIndexRouteImport } from './routes/_tools/qrcode/index'
import { Route as ToolsRegexTesterIndexRouteImport } from './routes/_tools/regex-tester/index'
import { Route as ToolsSqlFormatterIndexRouteImport } from './routes/_tools/sql-formatter/index'
import { Route as ToolsTextDiffIndexRouteImport } from './routes/_tools/text-diff/index'
import { Route as ToolsTimestampConverterIndexRouteImport } from './routes/_tools/timestamp-converter/index'
import { Route as ToolsUaCheckIndexRouteImport } from './routes/_tools/ua-check/index'
import { Route as ToolsUrlCodecIndexRouteImport } from './routes/_tools/url-codec/index'
import { Route as ToolsUuidGeneratorIndexRouteImport } from './routes/_tools/uuid-generator/index'
import { Route as ToolsWaLinkHelperIndexRouteImport } from './routes/_tools/wa-link-helper/index'
import { Route as ToolsYamlConverterIndexRouteImport } from './routes/_tools/yaml-converter/index'
import { Route as ToolsZippyImgIndexRouteImport } from './routes/_tools/zippy-img/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRouteRoute = ToolsRouteRouteImport.update({
  id: '/_tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const HomepageIndexRoute = HomepageIndexRouteImport.update({
  id: '/homepage/',
  path: '/homepage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAddToCalendarIndexRoute = ToolsAddToCalendarIndexRouteImport.update({
  id: '/add-to-calendar/',
  path: '/add-to-calendar/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsBase64IndexRoute = ToolsBase64IndexRouteImport.update({
  id: '/base64/',
  path: '/base64/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsCaseConverterIndexRoute = ToolsCaseConverterIndexRouteImport.update({
  id: '/case-converter/',
  path: '/case-converter/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsColorConverterIndexRoute =
  ToolsColorConverterIndexRouteImport.update({
    id: '/color-converter/',
    path: '/color-converter/',
    getParentRoute: () => ToolsRouteRoute,
  } as any)
const ToolsCronParserIndexRoute = ToolsCronParserIndexRouteImport.update({
  id: '/cron-parser/',
  path: '/cron-parser/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsCsvConverterIndexRoute = ToolsCsvConverterIndexRouteImport.update({
  id: '/csv-converter/',
  path: '/csv-converter/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsEvChargingIndexRoute = ToolsEvChargingIndexRouteImport.update({
  id: '/ev-charging/',
  path: '/ev-charging/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsHashGeneratorIndexRoute = ToolsHashGeneratorIndexRouteImport.update({
  id: '/hash-generator/',
  path: '/hash-generator/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsHtmlEntitiesIndexRoute = ToolsHtmlEntitiesIndexRouteImport.update({
  id: '/html-entities/',
  path: '/html-entities/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsJsPerfIndexRoute = ToolsJsPerfIndexRouteImport.update({
  id: '/js-perf/',
  path: '/js-perf/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsJsonFormatterIndexRoute = ToolsJsonFormatterIndexRouteImport.update({
  id: '/json-formatter/',
  path: '/json-formatter/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsJsonToTsIndexRoute = ToolsJsonToTsIndexRouteImport.update({
  id: '/json-to-ts/',
  path: '/json-to-ts/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsJwtDecoderIndexRoute = ToolsJwtDecoderIndexRouteImport.update({
  id: '/jwt-decoder/',
  path: '/jwt-decoder/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsMarkdownPreviewIndexRoute =
  ToolsMarkdownPreviewIndexRouteImport.update({
    id: '/markdown-preview/',
    path: '/markdown-preview/',
    getParentRoute: () => ToolsRouteRoute,
  } as any)
const ToolsNumberBaseIndexRoute = ToolsNumberBaseIndexRouteImport.update({
  id: '/number-base/',
  path: '/number-base/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsPasswordGeneratorIndexRoute =
  ToolsPasswordGeneratorIndexRouteImport.update({
    id: '/password-generator/',
    path: '/password-generator/',
    getParentRoute: () => ToolsRouteRoute,
  } as any)
const ToolsQrcodeIndexRoute = ToolsQrcodeIndexRouteImport.update({
  id: '/qrcode/',
  path: '/qrcode/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsRegexTesterIndexRoute = ToolsRegexTesterIndexRouteImport.update({
  id: '/regex-tester/',
  path: '/regex-tester/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsSqlFormatterIndexRoute = ToolsSqlFormatterIndexRouteImport.update({
  id: '/sql-formatter/',
  path: '/sql-formatter/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsTextDiffIndexRoute = ToolsTextDiffIndexRouteImport.update({
  id: '/text-diff/',
  path: '/text-diff/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsTimestampConverterIndexRoute =
  ToolsTimestampConverterIndexRouteImport.update({
    id: '/timestamp-converter/',
    path: '/timestamp-converter/',
    getParentRoute: () => ToolsRouteRoute,
  } as any)
const ToolsUaCheckIndexRoute = ToolsUaCheckIndexRouteImport.update({
  id: '/ua-check/',
  path: '/ua-check/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsUrlCodecIndexRoute = ToolsUrlCodecIndexRouteImport.update({
  id: '/url-codec/',
  path: '/url-codec/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsUuidGeneratorIndexRoute = ToolsUuidGeneratorIndexRouteImport.update({
  id: '/uuid-generator/',
  path: '/uuid-generator/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsWaLinkHelperIndexRoute = ToolsWaLinkHelperIndexRouteImport.update({
  id: '/wa-link-helper/',
  path: '/wa-link-helper/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsYamlConverterIndexRoute = ToolsYamlConverterIndexRouteImport.update({
  id: '/yaml-converter/',
  path: '/yaml-converter/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsZippyImgIndexRoute = ToolsZippyImgIndexRouteImport.update({
  id: '/zippy-img/',
  path: '/zippy-img/',
  getParentRoute: () => ToolsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/homepage/': typeof HomepageIndexRoute
  '/add-to-calendar/': typeof ToolsAddToCalendarIndexRoute
  '/base64/': typeof ToolsBase64IndexRoute
  '/case-converter/': typeof ToolsCaseConverterIndexRoute
  '/color-converter/': typeof ToolsColorConverterIndexRoute
  '/cron-parser/': typeof ToolsCronParserIndexRoute
  '/csv-converter/': typeof ToolsCsvConverterIndexRoute
  '/ev-charging/': typeof ToolsEvChargingIndexRoute
  '/hash-generator/': typeof ToolsHashGeneratorIndexRoute
  '/html-entities/': typeof ToolsHtmlEntitiesIndexRoute
  '/js-perf/': typeof ToolsJsPerfIndexRoute
  '/json-formatter/': typeof ToolsJsonFormatterIndexRoute
  '/json-to-ts/': typeof ToolsJsonToTsIndexRoute
  '/jwt-decoder/': typeof ToolsJwtDecoderIndexRoute
  '/markdown-preview/': typeof ToolsMarkdownPreviewIndexRoute
  '/number-base/': typeof ToolsNumberBaseIndexRoute
  '/password-generator/': typeof ToolsPasswordGeneratorIndexRoute
  '/qrcode/': typeof ToolsQrcodeIndexRoute
  '/regex-tester/': typeof ToolsRegexTesterIndexRoute
  '/sql-formatter/': typeof ToolsSqlFormatterIndexRoute
  '/text-diff/': typeof ToolsTextDiffIndexRoute
  '/timestamp-converter/': typeof ToolsTimestampConverterIndexRoute
  '/ua-check/': typeof ToolsUaCheckIndexRoute
  '/url-codec/': typeof ToolsUrlCodecIndexRoute
  '/uuid-generator/': typeof ToolsUuidGeneratorIndexRoute
  '/wa-link-helper/': typeof ToolsWaLinkHelperIndexRoute
  '/yaml-converter/': typeof ToolsYamlConverterIndexRoute
  '/zippy-img/': typeof ToolsZippyImgIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/homepage': typeof HomepageIndexRoute
  '/add-to-calendar': typeof ToolsAddToCalendarIndexRoute
  '/base64': typeof ToolsBase64IndexRoute
  '/case-converter': typeof ToolsCaseConverterIndexRoute
  '/color-converter': typeof ToolsColorConverterIndexRoute
  '/cron-parser': typeof ToolsCronParserIndexRoute
  '/csv-converter': typeof ToolsCsvConverterIndexRoute
  '/ev-charging': typeof ToolsEvChargingIndexRoute
  '/hash-generator': typeof ToolsHashGeneratorIndexRoute
  '/html-entities': typeof ToolsHtmlEntitiesIndexRoute
  '/js-perf': typeof ToolsJsPerfIndexRoute
  '/json-formatter': typeof ToolsJsonFormatterIndexRoute
  '/json-to-ts': typeof ToolsJsonToTsIndexRoute
  '/jwt-decoder': typeof ToolsJwtDecoderIndexRoute
  '/markdown-preview': typeof ToolsMarkdownPreviewIndexRoute
  '/number-base': typeof ToolsNumberBaseIndexRoute
  '/password-generator': typeof ToolsPasswordGeneratorIndexRoute
  '/qrcode': typeof ToolsQrcodeIndexRoute
  '/regex-tester': typeof ToolsRegexTesterIndexRoute
  '/sql-formatter': typeof ToolsSqlFormatterIndexRoute
  '/text-diff': typeof ToolsTextDiffIndexRoute
  '/timestamp-converter': typeof ToolsTimestampConverterIndexRoute
  '/ua-check': typeof ToolsUaCheckIndexRoute
  '/url-codec': typeof ToolsUrlCodecIndexRoute
  '/uuid-generator': typeof ToolsUuidGeneratorIndexRoute
  '/wa-link-helper': typeof ToolsWaLinkHelperIndexRoute
  '/yaml-converter': typeof ToolsYamlConverterIndexRoute
  '/zippy-img': typeof ToolsZippyImgIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tools': typeof ToolsRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/homepage/': typeof HomepageIndexRoute
  '/_tools/add-to-calendar/': typeof ToolsAddToCalendarIndexRoute
  '/_tools/base64/': typeof ToolsBase64IndexRoute
  '/_tools/case-converter/': typeof ToolsCaseConverterIndexRoute
  '/_tools/color-converter/': typeof ToolsColorConverterIndexRoute
  '/_tools/cron-parser/': typeof ToolsCronParserIndexRoute
  '/_tools/csv-converter/': typeof ToolsCsvConverterIndexRoute
  '/_tools/ev-charging/': typeof ToolsEvChargingIndexRoute
  '/_tools/hash-generator/': typeof ToolsHashGeneratorIndexRoute
  '/_tools/html-entities/': typeof ToolsHtmlEntitiesIndexRoute
  '/_tools/js-perf/': typeof ToolsJsPerfIndexRoute
  '/_tools/json-formatter/': typeof ToolsJsonFormatterIndexRoute
  '/_tools/json-to-ts/': typeof ToolsJsonToTsIndexRoute
  '/_tools/jwt-decoder/': typeof ToolsJwtDecoderIndexRoute
  '/_tools/markdown-preview/': typeof ToolsMarkdownPreviewIndexRoute
  '/_tools/number-base/': typeof ToolsNumberBaseIndexRoute
  '/_tools/password-generator/': typeof ToolsPasswordGeneratorIndexRoute
  '/_tools/qrcode/': typeof ToolsQrcodeIndexRoute
  '/_tools/regex-tester/': typeof ToolsRegexTesterIndexRoute
  '/_tools/sql-formatter/': typeof ToolsSqlFormatterIndexRoute
  '/_tools/text-diff/': typeof ToolsTextDiffIndexRoute
  '/_tools/timestamp-converter/': typeof ToolsTimestampConverterIndexRoute
  '/_tools/ua-check/': typeof ToolsUaCheckIndexRoute
  '/_tools/url-codec/': typeof ToolsUrlCodecIndexRoute
  '/_tools/uuid-generator/': typeof ToolsUuidGeneratorIndexRoute
  '/_tools/wa-link-helper/': typeof ToolsWaLinkHelperIndexRoute
  '/_tools/yaml-converter/': typeof ToolsYamlConverterIndexRoute
  '/_tools/zippy-img/': typeof ToolsZippyImgIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/homepage/'
    | '/add-to-calendar/'
    | '/base64/'
    | '/case-converter/'
    | '/color-converter/'
    | '/cron-parser/'
    | '/csv-converter/'
    | '/ev-charging/'
    | '/hash-generator/'
    | '/html-entities/'
    | '/js-perf/'
    | '/json-formatter/'
    | '/json-to-ts/'
    | '/jwt-decoder/'
    | '/markdown-preview/'
    | '/number-base/'
    | '/password-generator/'
    | '/qrcode/'
    | '/regex-tester/'
    | '/sql-formatter/'
    | '/text-diff/'
    | '/timestamp-converter/'
    | '/ua-check/'
    | '/url-codec/'
    | '/uuid-generator/'
    | '/wa-link-helper/'
    | '/yaml-converter/'
    | '/zippy-img/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/homepage'
    | '/add-to-calendar'
    | '/base64'
    | '/case-converter'
    | '/color-converter'
    | '/cron-parser'
    | '/csv-converter'
    | '/ev-charging'
    | '/hash-generator'
    | '/html-entities'
    | '/js-perf'
    | '/json-formatter'
    | '/json-to-ts'
    | '/jwt-decoder'
    | '/markdown-preview'
    | '/number-base'
    | '/password-generator'
    | '/qrcode'
    | '/regex-tester'
    | '/sql-formatter'
    | '/text-diff'
    | '/timestamp-converter'
    | '/ua-check'
    | '/url-codec'
    | '/uuid-generator'
    | '/wa-link-helper'
    | '/yaml-converter'
    | '/zippy-img'
  id:
    | '__root__'
    | '/'
    | '/_tools'
    | '/changelog'
    | '/homepage/'
    | '/_tools/add-to-calendar/'
    | '/_tools/base64/'
    | '/_tools/case-converter/'
    | '/_tools/color-converter/'
    | '/_tools/cron-parser/'
    | '/_tools/csv-converter/'
    | '/_tools/ev-charging/'
    | '/_tools/hash-generator/'
    | '/_tools/html-entities/'
    | '/_tools/js-perf/'
    | '/_tools/json-formatter/'
    | '/_tools/json-to-ts/'
    | '/_tools/jwt-decoder/'
    | '/_tools/markdown-preview/'
    | '/_tools/number-base/'
    | '/_tools/password-generator/'
    | '/_tools/qrcode/'
    | '/_tools/regex-tester/'
    | '/_tools/sql-formatter/'
    | '/_tools/text-diff/'
    | '/_tools/timestamp-converter/'
    | '/_tools/ua-check/'
    | '/_tools/url-codec/'
    | '/_tools/uuid-generator/'
    | '/_tools/wa-link-helper/'
    | '/_tools/yaml-converter/'
    | '/_tools/zippy-img/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsRouteRoute: typeof ToolsRouteRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  HomepageIndexRoute: typeof HomepageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tools': {
      id: '/_tools'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ToolsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homepage/': {
      id: '/homepage/'
      path: '/homepage'
      fullPath: '/homepage/'
      preLoaderRoute: typeof HomepageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tools/add-to-calendar/': {
      id: '/_tools/add-to-calendar/'
      path: '/add-to-calendar'
      fullPath: '/add-to-calendar/'
      preLoaderRoute: typeof ToolsAddToCalendarIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/base64/': {
      id: '/_tools/base64/'
      path: '/base64'
      fullPath: '/base64/'
      preLoaderRoute: typeof ToolsBase64IndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/case-converter/': {
      id: '/_tools/case-converter/'
      path: '/case-converter'
      fullPath: '/case-converter/'
      preLoaderRoute: typeof ToolsCaseConverterIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/color-converter/': {
      id: '/_tools/color-converter/'
      path: '/color-converter'
      fullPath: '/color-converter/'
      preLoaderRoute: typeof ToolsColorConverterIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/cron-parser/': {
      id: '/_tools/cron-parser/'
      path: '/cron-parser'
      fullPath: '/cron-parser/'
      preLoaderRoute: typeof ToolsCronParserIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/csv-converter/': {
      id: '/_tools/csv-converter/'
      path: '/csv-converter'
      fullPath: '/csv-converter/'
      preLoaderRoute: typeof ToolsCsvConverterIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/ev-charging/': {
      id: '/_tools/ev-charging/'
      path: '/ev-charging'
      fullPath: '/ev-charging/'
      preLoaderRoute: typeof ToolsEvChargingIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/hash-generator/': {
      id: '/_tools/hash-generator/'
      path: '/hash-generator'
      fullPath: '/hash-generator/'
      preLoaderRoute: typeof ToolsHashGeneratorIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/html-entities/': {
      id: '/_tools/html-entities/'
      path: '/html-entities'
      fullPath: '/html-entities/'
      preLoaderRoute: typeof ToolsHtmlEntitiesIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/js-perf/': {
      id: '/_tools/js-perf/'
      path: '/js-perf'
      fullPath: '/js-perf/'
      preLoaderRoute: typeof ToolsJsPerfIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/json-formatter/': {
      id: '/_tools/json-formatter/'
      path: '/json-formatter'
      fullPath: '/json-formatter/'
      preLoaderRoute: typeof ToolsJsonFormatterIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/json-to-ts/': {
      id: '/_tools/json-to-ts/'
      path: '/json-to-ts'
      fullPath: '/json-to-ts/'
      preLoaderRoute: typeof ToolsJsonToTsIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/jwt-decoder/': {
      id: '/_tools/jwt-decoder/'
      path: '/jwt-decoder'
      fullPath: '/jwt-decoder/'
      preLoaderRoute: typeof ToolsJwtDecoderIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/markdown-preview/': {
      id: '/_tools/markdown-preview/'
      path: '/markdown-preview'
      fullPath: '/markdown-preview/'
      preLoaderRoute: typeof ToolsMarkdownPreviewIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/number-base/': {
      id: '/_tools/number-base/'
      path: '/number-base'
      fullPath: '/number-base/'
      preLoaderRoute: typeof ToolsNumberBaseIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/password-generator/': {
      id: '/_tools/password-generator/'
      path: '/password-generator'
      fullPath: '/password-generator/'
      preLoaderRoute: typeof ToolsPasswordGeneratorIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/qrcode/': {
      id: '/_tools/qrcode/'
      path: '/qrcode'
      fullPath: '/qrcode/'
      preLoaderRoute: typeof ToolsQrcodeIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/regex-tester/': {
      id: '/_tools/regex-tester/'
      path: '/regex-tester'
      fullPath: '/regex-tester/'
      preLoaderRoute: typeof ToolsRegexTesterIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/sql-formatter/': {
      id: '/_tools/sql-formatter/'
      path: '/sql-formatter'
      fullPath: '/sql-formatter/'
      preLoaderRoute: typeof ToolsSqlFormatterIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/text-diff/': {
      id: '/_tools/text-diff/'
      path: '/text-diff'
      fullPath: '/text-diff/'
      preLoaderRoute: typeof ToolsTextDiffIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/timestamp-converter/': {
      id: '/_tools/timestamp-converter/'
      path: '/timestamp-converter'
      fullPath: '/timestamp-converter/'
      preLoaderRoute: typeof ToolsTimestampConverterIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/ua-check/': {
      id: '/_tools/ua-check/'
      path: '/ua-check'
      fullPath: '/ua-check/'
      preLoaderRoute: typeof ToolsUaCheckIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/url-codec/': {
      id: '/_tools/url-codec/'
      path: '/url-codec'
      fullPath: '/url-codec/'
      preLoaderRoute: typeof ToolsUrlCodecIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/uuid-generator/': {
      id: '/_tools/uuid-generator/'
      path: '/uuid-generator'
      fullPath: '/uuid-generator/'
      preLoaderRoute: typeof ToolsUuidGeneratorIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/wa-link-helper/': {
      id: '/_tools/wa-link-helper/'
      path: '/wa-link-helper'
      fullPath: '/wa-link-helper/'
      preLoaderRoute: typeof ToolsWaLinkHelperIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/yaml-converter/': {
      id: '/_tools/yaml-converter/'
      path: '/yaml-converter'
      fullPath: '/yaml-converter/'
      preLoaderRoute: typeof ToolsYamlConverterIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/zippy-img/': {
      id: '/_tools/zippy-img/'
      path: '/zippy-img'
      fullPath: '/zippy-img/'
      preLoaderRoute: typeof ToolsZippyImgIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
  }
}

interface ToolsRouteRouteChildren {
  ToolsAddToCalendarIndexRoute: typeof ToolsAddToCalendarIndexRoute
  ToolsBase64IndexRoute: typeof ToolsBase64IndexRoute
  ToolsCaseConverterIndexRoute: typeof ToolsCaseConverterIndexRoute
  ToolsColorConverterIndexRoute: typeof ToolsColorConverterIndexRoute
  ToolsCronParserIndexRoute: typeof ToolsCronParserIndexRoute
  ToolsCsvConverterIndexRoute: typeof ToolsCsvConverterIndexRoute
  ToolsEvChargingIndexRoute: typeof ToolsEvChargingIndexRoute
  ToolsHashGeneratorIndexRoute: typeof ToolsHashGeneratorIndexRoute
  ToolsHtmlEntitiesIndexRoute: typeof ToolsHtmlEntitiesIndexRoute
  ToolsJsPerfIndexRoute: typeof ToolsJsPerfIndexRoute
  ToolsJsonFormatterIndexRoute: typeof ToolsJsonFormatterIndexRoute
  ToolsJsonToTsIndexRoute: typeof ToolsJsonToTsIndexRoute
  ToolsJwtDecoderIndexRoute: typeof ToolsJwtDecoderIndexRoute
  ToolsMarkdownPreviewIndexRoute: typeof ToolsMarkdownPreviewIndexRoute
  ToolsNumberBaseIndexRoute: typeof ToolsNumberBaseIndexRoute
  ToolsPasswordGeneratorIndexRoute: typeof ToolsPasswordGeneratorIndexRoute
  ToolsQrcodeIndexRoute: typeof ToolsQrcodeIndexRoute
  ToolsRegexTesterIndexRoute: typeof ToolsRegexTesterIndexRoute
  ToolsSqlFormatterIndexRoute: typeof ToolsSqlFormatterIndexRoute
  ToolsTextDiffIndexRoute: typeof ToolsTextDiffIndexRoute
  ToolsTimestampConverterIndexRoute: typeof ToolsTimestampConverterIndexRoute
  ToolsUaCheckIndexRoute: typeof ToolsUaCheckIndexRoute
  ToolsUrlCodecIndexRoute: typeof ToolsUrlCodecIndexRoute
  ToolsUuidGeneratorIndexRoute: typeof ToolsUuidGeneratorIndexRoute
  ToolsWaLinkHelperIndexRoute: typeof ToolsWaLinkHelperIndexRoute
  ToolsYamlConverterIndexRoute: typeof ToolsYamlConverterIndexRoute
  ToolsZippyImgIndexRoute: typeof ToolsZippyImgIndexRoute
}

const ToolsRouteRouteChildren: ToolsRouteRouteChildren = {
  ToolsAddToCalendarIndexRoute: ToolsAddToCalendarIndexRoute,
  ToolsBase64IndexRoute: ToolsBase64IndexRoute,
  ToolsCaseConverterIndexRoute: ToolsCaseConverterIndexRoute,
  ToolsColorConverterIndexRoute: ToolsColorConverterIndexRoute,
  ToolsCronParserIndexRoute: ToolsCronParserIndexRoute,
  ToolsCsvConverterIndexRoute: ToolsCsvConverterIndexRoute,
  ToolsEvChargingIndexRoute: ToolsEvChargingIndexRoute,
  ToolsHashGeneratorIndexRoute: ToolsHashGeneratorIndexRoute,
  ToolsHtmlEntitiesIndexRoute: ToolsHtmlEntitiesIndexRoute,
  ToolsJsPerfIndexRoute: ToolsJsPerfIndexRoute,
  ToolsJsonFormatterIndexRoute: ToolsJsonFormatterIndexRoute,
  ToolsJsonToTsIndexRoute: ToolsJsonToTsIndexRoute,
  ToolsJwtDecoderIndexRoute: ToolsJwtDecoderIndexRoute,
  ToolsMarkdownPreviewIndexRoute: ToolsMarkdownPreviewIndexRoute,
  ToolsNumberBaseIndexRoute: ToolsNumberBaseIndexRoute,
  ToolsPasswordGeneratorIndexRoute: ToolsPasswordGeneratorIndexRoute,
  ToolsQrcodeIndexRoute: ToolsQrcodeIndexRoute,
  ToolsRegexTesterIndexRoute: ToolsRegexTesterIndexRoute,
  ToolsSqlFormatterIndexRoute: ToolsSqlFormatterIndexRoute,
  ToolsTextDiffIndexRoute: ToolsTextDiffIndexRoute,
  ToolsTimestampConverterIndexRoute: ToolsTimestampConverterIndexRoute,
  ToolsUaCheckIndexRoute: ToolsUaCheckIndexRoute,
  ToolsUrlCodecIndexRoute: ToolsUrlCodecIndexRoute,
  ToolsUuidGeneratorIndexRoute: ToolsUuidGeneratorIndexRoute,
  ToolsWaLinkHelperIndexRoute: ToolsWaLinkHelperIndexRoute,
  ToolsYamlConverterIndexRoute: ToolsYamlConverterIndexRoute,
  ToolsZippyImgIndexRoute: ToolsZippyImgIndexRoute,
}

const ToolsRouteRouteWithChildren = ToolsRouteRoute._addFileChildren(
  ToolsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsRouteRoute: ToolsRouteRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  HomepageIndexRoute: HomepageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
