/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsRouteRouteImport } from './routes/_tools/route'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as HomepageIndexRouteImport } from './routes/homepage/index'
import { Route as ToolsAddToCalendarIndexRouteImport } from './routes/_tools/add-to-calendar/index'
import { Route as ToolsBase64IndexRouteImport } from './routes/_tools/base64/index'
import { Route as ToolsCaseConverterIndexRouteImport } from './routes/_tools/case-converter/index'
import { Route as ToolsColorConverterIndexRouteImport } from './routes/_tools/color-converter/index'
import { Route as ToolsCsvConverterIndexRouteImport } from './routes/_tools/csv-converter/index'
import { Route as ToolsEvChargingIndexRouteImport } from './routes/_tools/ev-charging/index'
import { Route as ToolsHashGeneratorIndexRouteImport } from './routes/_tools/hash-generator/index'
import { Route as ToolsJsPerfIndexRouteImport } from './routes/_tools/js-perf/index'
import { Route as ToolsJsonFormatterIndexRouteImport } from './routes/_tools/json-formatter/index'
import { Route as ToolsJsonToTsIndexRouteImport } from './routes/_tools/json-to-ts/index'
import { Route as ToolsJwtDecoderIndexRouteImport } from './routes/_tools/jwt-decoder/index'
import { Route as ToolsPasswordGeneratorIndexRouteImport } from './routes/_tools/password-generator/index'
import { Route as ToolsQrcodeIndexRouteImport } from './routes/_tools/qrcode/index'
import { Route as ToolsRegexTesterIndexRouteImport } from './routes/_tools/regex-tester/index'
import { Route as ToolsTextDiffIndexRouteImport } from './routes/_tools/text-diff/index'
import { Route as ToolsTimestampConverterIndexRouteImport } from './routes/_tools/timestamp-converter/index'
import { Route as ToolsUaCheckIndexRouteImport } from './routes/_tools/ua-check/index'
import { Route as ToolsUuidGeneratorIndexRouteImport } from './routes/_tools/uuid-generator/index'
import { Route as ToolsWaLinkHelperIndexRouteImport } from './routes/_tools/wa-link-helper/index'
import { Route as ToolsZippyImgIndexRouteImport } from './routes/_tools/zippy-img/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRouteRoute = ToolsRouteRouteImport.update({
  id: '/_tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const HomepageIndexRoute = HomepageIndexRouteImport.update({
  id: '/homepage/',
  path: '/homepage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAddToCalendarIndexRoute = ToolsAddToCalendarIndexRouteImport.update({
  id: '/add-to-calendar/',
  path: '/add-to-calendar/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsBase64IndexRoute = ToolsBase64IndexRouteImport.update({
  id: '/base64/',
  path: '/base64/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsCaseConverterIndexRoute = ToolsCaseConverterIndexRouteImport.update({
  id: '/case-converter/',
  path: '/case-converter/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsColorConverterIndexRoute =
  ToolsColorConverterIndexRouteImport.update({
    id: '/color-converter/',
    path: '/color-converter/',
    getParentRoute: () => ToolsRouteRoute,
  } as any)
const ToolsCsvConverterIndexRoute = ToolsCsvConverterIndexRouteImport.update({
  id: '/csv-converter/',
  path: '/csv-converter/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsEvChargingIndexRoute = ToolsEvChargingIndexRouteImport.update({
  id: '/ev-charging/',
  path: '/ev-charging/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsHashGeneratorIndexRoute = ToolsHashGeneratorIndexRouteImport.update({
  id: '/hash-generator/',
  path: '/hash-generator/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsJsPerfIndexRoute = ToolsJsPerfIndexRouteImport.update({
  id: '/js-perf/',
  path: '/js-perf/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsJsonFormatterIndexRoute = ToolsJsonFormatterIndexRouteImport.update({
  id: '/json-formatter/',
  path: '/json-formatter/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsJsonToTsIndexRoute = ToolsJsonToTsIndexRouteImport.update({
  id: '/json-to-ts/',
  path: '/json-to-ts/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsJwtDecoderIndexRoute = ToolsJwtDecoderIndexRouteImport.update({
  id: '/jwt-decoder/',
  path: '/jwt-decoder/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsPasswordGeneratorIndexRoute =
  ToolsPasswordGeneratorIndexRouteImport.update({
    id: '/password-generator/',
    path: '/password-generator/',
    getParentRoute: () => ToolsRouteRoute,
  } as any)
const ToolsQrcodeIndexRoute = ToolsQrcodeIndexRouteImport.update({
  id: '/qrcode/',
  path: '/qrcode/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsRegexTesterIndexRoute = ToolsRegexTesterIndexRouteImport.update({
  id: '/regex-tester/',
  path: '/regex-tester/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsTextDiffIndexRoute = ToolsTextDiffIndexRouteImport.update({
  id: '/text-diff/',
  path: '/text-diff/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsTimestampConverterIndexRoute =
  ToolsTimestampConverterIndexRouteImport.update({
    id: '/timestamp-converter/',
    path: '/timestamp-converter/',
    getParentRoute: () => ToolsRouteRoute,
  } as any)
const ToolsUaCheckIndexRoute = ToolsUaCheckIndexRouteImport.update({
  id: '/ua-check/',
  path: '/ua-check/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsUuidGeneratorIndexRoute = ToolsUuidGeneratorIndexRouteImport.update({
  id: '/uuid-generator/',
  path: '/uuid-generator/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsWaLinkHelperIndexRoute = ToolsWaLinkHelperIndexRouteImport.update({
  id: '/wa-link-helper/',
  path: '/wa-link-helper/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsZippyImgIndexRoute = ToolsZippyImgIndexRouteImport.update({
  id: '/zippy-img/',
  path: '/zippy-img/',
  getParentRoute: () => ToolsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/homepage/': typeof HomepageIndexRoute
  '/add-to-calendar/': typeof ToolsAddToCalendarIndexRoute
  '/base64/': typeof ToolsBase64IndexRoute
  '/case-converter/': typeof ToolsCaseConverterIndexRoute
  '/color-converter/': typeof ToolsColorConverterIndexRoute
  '/csv-converter/': typeof ToolsCsvConverterIndexRoute
  '/ev-charging/': typeof ToolsEvChargingIndexRoute
  '/hash-generator/': typeof ToolsHashGeneratorIndexRoute
  '/js-perf/': typeof ToolsJsPerfIndexRoute
  '/json-formatter/': typeof ToolsJsonFormatterIndexRoute
  '/json-to-ts/': typeof ToolsJsonToTsIndexRoute
  '/jwt-decoder/': typeof ToolsJwtDecoderIndexRoute
  '/password-generator/': typeof ToolsPasswordGeneratorIndexRoute
  '/qrcode/': typeof ToolsQrcodeIndexRoute
  '/regex-tester/': typeof ToolsRegexTesterIndexRoute
  '/text-diff/': typeof ToolsTextDiffIndexRoute
  '/timestamp-converter/': typeof ToolsTimestampConverterIndexRoute
  '/ua-check/': typeof ToolsUaCheckIndexRoute
  '/uuid-generator/': typeof ToolsUuidGeneratorIndexRoute
  '/wa-link-helper/': typeof ToolsWaLinkHelperIndexRoute
  '/zippy-img/': typeof ToolsZippyImgIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/homepage': typeof HomepageIndexRoute
  '/add-to-calendar': typeof ToolsAddToCalendarIndexRoute
  '/base64': typeof ToolsBase64IndexRoute
  '/case-converter': typeof ToolsCaseConverterIndexRoute
  '/color-converter': typeof ToolsColorConverterIndexRoute
  '/csv-converter': typeof ToolsCsvConverterIndexRoute
  '/ev-charging': typeof ToolsEvChargingIndexRoute
  '/hash-generator': typeof ToolsHashGeneratorIndexRoute
  '/js-perf': typeof ToolsJsPerfIndexRoute
  '/json-formatter': typeof ToolsJsonFormatterIndexRoute
  '/json-to-ts': typeof ToolsJsonToTsIndexRoute
  '/jwt-decoder': typeof ToolsJwtDecoderIndexRoute
  '/password-generator': typeof ToolsPasswordGeneratorIndexRoute
  '/qrcode': typeof ToolsQrcodeIndexRoute
  '/regex-tester': typeof ToolsRegexTesterIndexRoute
  '/text-diff': typeof ToolsTextDiffIndexRoute
  '/timestamp-converter': typeof ToolsTimestampConverterIndexRoute
  '/ua-check': typeof ToolsUaCheckIndexRoute
  '/uuid-generator': typeof ToolsUuidGeneratorIndexRoute
  '/wa-link-helper': typeof ToolsWaLinkHelperIndexRoute
  '/zippy-img': typeof ToolsZippyImgIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tools': typeof ToolsRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/homepage/': typeof HomepageIndexRoute
  '/_tools/add-to-calendar/': typeof ToolsAddToCalendarIndexRoute
  '/_tools/base64/': typeof ToolsBase64IndexRoute
  '/_tools/case-converter/': typeof ToolsCaseConverterIndexRoute
  '/_tools/color-converter/': typeof ToolsColorConverterIndexRoute
  '/_tools/csv-converter/': typeof ToolsCsvConverterIndexRoute
  '/_tools/ev-charging/': typeof ToolsEvChargingIndexRoute
  '/_tools/hash-generator/': typeof ToolsHashGeneratorIndexRoute
  '/_tools/js-perf/': typeof ToolsJsPerfIndexRoute
  '/_tools/json-formatter/': typeof ToolsJsonFormatterIndexRoute
  '/_tools/json-to-ts/': typeof ToolsJsonToTsIndexRoute
  '/_tools/jwt-decoder/': typeof ToolsJwtDecoderIndexRoute
  '/_tools/password-generator/': typeof ToolsPasswordGeneratorIndexRoute
  '/_tools/qrcode/': typeof ToolsQrcodeIndexRoute
  '/_tools/regex-tester/': typeof ToolsRegexTesterIndexRoute
  '/_tools/text-diff/': typeof ToolsTextDiffIndexRoute
  '/_tools/timestamp-converter/': typeof ToolsTimestampConverterIndexRoute
  '/_tools/ua-check/': typeof ToolsUaCheckIndexRoute
  '/_tools/uuid-generator/': typeof ToolsUuidGeneratorIndexRoute
  '/_tools/wa-link-helper/': typeof ToolsWaLinkHelperIndexRoute
  '/_tools/zippy-img/': typeof ToolsZippyImgIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/homepage/'
    | '/add-to-calendar/'
    | '/base64/'
    | '/case-converter/'
    | '/color-converter/'
    | '/csv-converter/'
    | '/ev-charging/'
    | '/hash-generator/'
    | '/js-perf/'
    | '/json-formatter/'
    | '/json-to-ts/'
    | '/jwt-decoder/'
    | '/password-generator/'
    | '/qrcode/'
    | '/regex-tester/'
    | '/text-diff/'
    | '/timestamp-converter/'
    | '/ua-check/'
    | '/uuid-generator/'
    | '/wa-link-helper/'
    | '/zippy-img/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/homepage'
    | '/add-to-calendar'
    | '/base64'
    | '/case-converter'
    | '/color-converter'
    | '/csv-converter'
    | '/ev-charging'
    | '/hash-generator'
    | '/js-perf'
    | '/json-formatter'
    | '/json-to-ts'
    | '/jwt-decoder'
    | '/password-generator'
    | '/qrcode'
    | '/regex-tester'
    | '/text-diff'
    | '/timestamp-converter'
    | '/ua-check'
    | '/uuid-generator'
    | '/wa-link-helper'
    | '/zippy-img'
  id:
    | '__root__'
    | '/'
    | '/_tools'
    | '/changelog'
    | '/homepage/'
    | '/_tools/add-to-calendar/'
    | '/_tools/base64/'
    | '/_tools/case-converter/'
    | '/_tools/color-converter/'
    | '/_tools/csv-converter/'
    | '/_tools/ev-charging/'
    | '/_tools/hash-generator/'
    | '/_tools/js-perf/'
    | '/_tools/json-formatter/'
    | '/_tools/json-to-ts/'
    | '/_tools/jwt-decoder/'
    | '/_tools/password-generator/'
    | '/_tools/qrcode/'
    | '/_tools/regex-tester/'
    | '/_tools/text-diff/'
    | '/_tools/timestamp-converter/'
    | '/_tools/ua-check/'
    | '/_tools/uuid-generator/'
    | '/_tools/wa-link-helper/'
    | '/_tools/zippy-img/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsRouteRoute: typeof ToolsRouteRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  HomepageIndexRoute: typeof HomepageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tools': {
      id: '/_tools'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ToolsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homepage/': {
      id: '/homepage/'
      path: '/homepage'
      fullPath: '/homepage/'
      preLoaderRoute: typeof HomepageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tools/add-to-calendar/': {
      id: '/_tools/add-to-calendar/'
      path: '/add-to-calendar'
      fullPath: '/add-to-calendar/'
      preLoaderRoute: typeof ToolsAddToCalendarIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/base64/': {
      id: '/_tools/base64/'
      path: '/base64'
      fullPath: '/base64/'
      preLoaderRoute: typeof ToolsBase64IndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/case-converter/': {
      id: '/_tools/case-converter/'
      path: '/case-converter'
      fullPath: '/case-converter/'
      preLoaderRoute: typeof ToolsCaseConverterIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/color-converter/': {
      id: '/_tools/color-converter/'
      path: '/color-converter'
      fullPath: '/color-converter/'
      preLoaderRoute: typeof ToolsColorConverterIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/csv-converter/': {
      id: '/_tools/csv-converter/'
      path: '/csv-converter'
      fullPath: '/csv-converter/'
      preLoaderRoute: typeof ToolsCsvConverterIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/ev-charging/': {
      id: '/_tools/ev-charging/'
      path: '/ev-charging'
      fullPath: '/ev-charging/'
      preLoaderRoute: typeof ToolsEvChargingIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/hash-generator/': {
      id: '/_tools/hash-generator/'
      path: '/hash-generator'
      fullPath: '/hash-generator/'
      preLoaderRoute: typeof ToolsHashGeneratorIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/js-perf/': {
      id: '/_tools/js-perf/'
      path: '/js-perf'
      fullPath: '/js-perf/'
      preLoaderRoute: typeof ToolsJsPerfIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/json-formatter/': {
      id: '/_tools/json-formatter/'
      path: '/json-formatter'
      fullPath: '/json-formatter/'
      preLoaderRoute: typeof ToolsJsonFormatterIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/json-to-ts/': {
      id: '/_tools/json-to-ts/'
      path: '/json-to-ts'
      fullPath: '/json-to-ts/'
      preLoaderRoute: typeof ToolsJsonToTsIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/jwt-decoder/': {
      id: '/_tools/jwt-decoder/'
      path: '/jwt-decoder'
      fullPath: '/jwt-decoder/'
      preLoaderRoute: typeof ToolsJwtDecoderIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/password-generator/': {
      id: '/_tools/password-generator/'
      path: '/password-generator'
      fullPath: '/password-generator/'
      preLoaderRoute: typeof ToolsPasswordGeneratorIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/qrcode/': {
      id: '/_tools/qrcode/'
      path: '/qrcode'
      fullPath: '/qrcode/'
      preLoaderRoute: typeof ToolsQrcodeIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/regex-tester/': {
      id: '/_tools/regex-tester/'
      path: '/regex-tester'
      fullPath: '/regex-tester/'
      preLoaderRoute: typeof ToolsRegexTesterIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/text-diff/': {
      id: '/_tools/text-diff/'
      path: '/text-diff'
      fullPath: '/text-diff/'
      preLoaderRoute: typeof ToolsTextDiffIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/timestamp-converter/': {
      id: '/_tools/timestamp-converter/'
      path: '/timestamp-converter'
      fullPath: '/timestamp-converter/'
      preLoaderRoute: typeof ToolsTimestampConverterIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/ua-check/': {
      id: '/_tools/ua-check/'
      path: '/ua-check'
      fullPath: '/ua-check/'
      preLoaderRoute: typeof ToolsUaCheckIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/uuid-generator/': {
      id: '/_tools/uuid-generator/'
      path: '/uuid-generator'
      fullPath: '/uuid-generator/'
      preLoaderRoute: typeof ToolsUuidGeneratorIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/wa-link-helper/': {
      id: '/_tools/wa-link-helper/'
      path: '/wa-link-helper'
      fullPath: '/wa-link-helper/'
      preLoaderRoute: typeof ToolsWaLinkHelperIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/zippy-img/': {
      id: '/_tools/zippy-img/'
      path: '/zippy-img'
      fullPath: '/zippy-img/'
      preLoaderRoute: typeof ToolsZippyImgIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
  }
}

interface ToolsRouteRouteChildren {
  ToolsAddToCalendarIndexRoute: typeof ToolsAddToCalendarIndexRoute
  ToolsBase64IndexRoute: typeof ToolsBase64IndexRoute
  ToolsCaseConverterIndexRoute: typeof ToolsCaseConverterIndexRoute
  ToolsColorConverterIndexRoute: typeof ToolsColorConverterIndexRoute
  ToolsCsvConverterIndexRoute: typeof ToolsCsvConverterIndexRoute
  ToolsEvChargingIndexRoute: typeof ToolsEvChargingIndexRoute
  ToolsHashGeneratorIndexRoute: typeof ToolsHashGeneratorIndexRoute
  ToolsJsPerfIndexRoute: typeof ToolsJsPerfIndexRoute
  ToolsJsonFormatterIndexRoute: typeof ToolsJsonFormatterIndexRoute
  ToolsJsonToTsIndexRoute: typeof ToolsJsonToTsIndexRoute
  ToolsJwtDecoderIndexRoute: typeof ToolsJwtDecoderIndexRoute
  ToolsPasswordGeneratorIndexRoute: typeof ToolsPasswordGeneratorIndexRoute
  ToolsQrcodeIndexRoute: typeof ToolsQrcodeIndexRoute
  ToolsRegexTesterIndexRoute: typeof ToolsRegexTesterIndexRoute
  ToolsTextDiffIndexRoute: typeof ToolsTextDiffIndexRoute
  ToolsTimestampConverterIndexRoute: typeof ToolsTimestampConverterIndexRoute
  ToolsUaCheckIndexRoute: typeof ToolsUaCheckIndexRoute
  ToolsUuidGeneratorIndexRoute: typeof ToolsUuidGeneratorIndexRoute
  ToolsWaLinkHelperIndexRoute: typeof ToolsWaLinkHelperIndexRoute
  ToolsZippyImgIndexRoute: typeof ToolsZippyImgIndexRoute
}

const ToolsRouteRouteChildren: ToolsRouteRouteChildren = {
  ToolsAddToCalendarIndexRoute: ToolsAddToCalendarIndexRoute,
  ToolsBase64IndexRoute: ToolsBase64IndexRoute,
  ToolsCaseConverterIndexRoute: ToolsCaseConverterIndexRoute,
  ToolsColorConverterIndexRoute: ToolsColorConverterIndexRoute,
  ToolsCsvConverterIndexRoute: ToolsCsvConverterIndexRoute,
  ToolsEvChargingIndexRoute: ToolsEvChargingIndexRoute,
  ToolsHashGeneratorIndexRoute: ToolsHashGeneratorIndexRoute,
  ToolsJsPerfIndexRoute: ToolsJsPerfIndexRoute,
  ToolsJsonFormatterIndexRoute: ToolsJsonFormatterIndexRoute,
  ToolsJsonToTsIndexRoute: ToolsJsonToTsIndexRoute,
  ToolsJwtDecoderIndexRoute: ToolsJwtDecoderIndexRoute,
  ToolsPasswordGeneratorIndexRoute: ToolsPasswordGeneratorIndexRoute,
  ToolsQrcodeIndexRoute: ToolsQrcodeIndexRoute,
  ToolsRegexTesterIndexRoute: ToolsRegexTesterIndexRoute,
  ToolsTextDiffIndexRoute: ToolsTextDiffIndexRoute,
  ToolsTimestampConverterIndexRoute: ToolsTimestampConverterIndexRoute,
  ToolsUaCheckIndexRoute: ToolsUaCheckIndexRoute,
  ToolsUuidGeneratorIndexRoute: ToolsUuidGeneratorIndexRoute,
  ToolsWaLinkHelperIndexRoute: ToolsWaLinkHelperIndexRoute,
  ToolsZippyImgIndexRoute: ToolsZippyImgIndexRoute,
}

const ToolsRouteRouteWithChildren = ToolsRouteRoute._addFileChildren(
  ToolsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsRouteRoute: ToolsRouteRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  HomepageIndexRoute: HomepageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
